In [2]:
import sys
from pathlib import Path

# This finds the parent directory of your notebook (the project root)
root_path = Path.cwd().parent
if str(root_path) not in sys.path:
    sys.path.append(str(root_path))

from src.loader.data_loader import get_merged_data

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
import warnings
warnings.filterwarnings('ignore')

In [11]:
df = get_merged_data(path_to_data="../data/raw/")
df.head()

,disasterNumber,totalObligatedAmountPa,totalObligatedAmountCatAb,totalObligatedAmountCatC2g,totalAmountIhpApproved,totalObligatedAmountHmgp,totalNumberIaApproved,declarationType,incidentType,stateCode,region,declarationDate,declarationRequestDate,incidentBeginDate,incidentEndDate,iaProgramDeclared,paProgramDeclared,hmProgramDeclared,totalObligated
0,3601,NaN,NaN,NaN,NaN,NaN,NaN,Emergency,Tropical Storm,GU,9,2023-10-08T00:00:00.000Z,2023-10-08T00:00:00.000Z,2023-10-08T00:00:00.000Z,2023-10-16T00:00:00.000Z,0.0,1.0,0.0,NaN
1,3602,NaN,NaN,NaN,NaN,NaN,NaN,Emergency,Tropical Storm,MP,9,2023-10-08T00:00:00.000Z,2023-10-08T00:00:00.000Z,2023-10-09T00:00:00.000Z,2023-10-16T00:00:00.000Z,0.0,1.0,0.0,NaN
2,1981,2.243558e+08,94967791.86,1.197739e+08,95754618.67,71549737.00,7469.0,Major Disaster,Flood,ND,8,2011-05-10T00:00:00.000Z,2011-05-06T00:00:00.000Z,2011-02-14T00:00:00.000Z,2011-07-20T00:00:00.000Z,0.0,1.0,1.0,2.243454e+08
3,1802,1.881275e+07,13423088.38,4.869890e+06,NaN,2710679.00,NaN,Major Disaster,Severe Storm,KY,4,2008-10-09T00:00:00.000Z,2008-09-26T00:00:00.000Z,2008-09-12T00:00:00.000Z,2008-09-14T00:00:00.000Z,0.0,1.0,1.0,1.881275e+07
4,4317,7.731984e+07,11526563.99,6.437977e+07,12527583.31,17801245.73,1978.0,Major Disaster,Flood,MO,7,2017-06-02T00:00:00.000Z,2017-05-24T00:00:00.000Z,2017-04-28T00:00:00.000Z,2017-05-11T00:00:00.000Z,0.0,1.0,1.0,7.732569e+07

In [15]:
checks = df[df['totalObligatedAmountPa'].notna()][['disasterNumber','totalObligatedAmountPa', 'totalObligatedAmountCatAb', 'totalObligatedAmountCatC2g']]
checks['sum'] = checks['totalObligatedAmountCatAb'] + checks['totalObligatedAmountCatC2g']
checks.head(10)

,disasterNumber,totalObligatedAmountPa,totalObligatedAmountCatAb,totalObligatedAmountCatC2g,sum
2,1981,2.243558e+08,9.496779e+07,1.197739e+08,2.147417e+08
3,1802,1.881275e+07,1.342309e+07,4.869890e+06,1.829298e+07
4,4317,7.731984e+07,1.152656e+07,6.437977e+07,7.590634e+07
5,1292,2.981058e+08,1.436027e+08,1.504852e+08,2.940879e+08
6,1255,4.507775e+06,1.401616e+06,3.106159e+06,4.507775e+06
7,3163,5.380816e+06,5.369404e+06,NaN,NaN
8,4898,3.863272e+06,3.863272e+06,NaN,NaN
9,3187,1.597088e+06,1.616903e+06,NaN,NaN
10,4015,5.553128e+06,3.549147e+06,1.760213e+06,5.309359e+06
11,4359,3.401980e+07,1.189389e+06,2.874487e+07,2.993426e+07

In [12]:
df.isna().sum()

disasterNumber                   0
totalObligatedAmountPa         924
totalObligatedAmountCatAb     1185
totalObligatedAmountCatC2g    2361
totalAmountIhpApproved        3308
totalObligatedAmountHmgp      1098
totalNumberIaApproved         3308
declarationType                  0
incidentType                     0
stateCode                        0
region                           0
declarationDate                  0
declarationRequestDate           1
incidentBeginDate                0
incidentEndDate                296
iaProgramDeclared              251
paProgramDeclared              251
hmProgramDeclared              251
totalObligated                2144
dtype: int64

In [16]:
df = df.drop(columns=['totalObligatedAmountCatAb', 'totalObligatedAmountCatC2g','totalObligated'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3909 entries, 0 to 3908
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   disasterNumber            3909 non-null   int64
 1   totalObligatedAmountPa    2985 non-null   float64
 2   totalAmountIhpApproved    601 non-null    float64
 3   totalObligatedAmountHmgp  2811 non-null   float64
 4   totalNumberIaApproved     601 non-null    float64
 5   declarationType           3909 non-null   str
 6   incidentType              3909 non-null   str
 7   stateCode                 3909 non-null   str
 8   region                    3909 non-null   int64
 9   declarationDate           3909 non-null   str
 10  declarationRequestDate    3908 non-null   str
 11  incidentBeginDate         3909 non-null   str
 12  incidentEndDate           3613 non-null   str
 13  iaProgramDeclared         3658 non-null   float64
 14  paProgramDeclared         3658 non-null   float64
 15  hmProgramDeclared         3658 non-null   float64
dtypes: float64(7), int64(2), str(7)
memory usage: 488.8 KB

In [17]:
df.head()

,disasterNumber,totalObligatedAmountPa,totalAmountIhpApproved,totalObligatedAmountHmgp,totalNumberIaApproved,declarationType,incidentType,stateCode,region,declarationDate,declarationRequestDate,incidentBeginDate,incidentEndDate,iaProgramDeclared,paProgramDeclared,hmProgramDeclared
0,3601,NaN,NaN,NaN,NaN,Emergency,Tropical Storm,GU,9,2023-10-08T00:00:00.000Z,2023-10-08T00:00:00.000Z,2023-10-08T00:00:00.000Z,2023-10-16T00:00:00.000Z,0.0,1.0,0.0
1,3602,NaN,NaN,NaN,NaN,Emergency,Tropical Storm,MP,9,2023-10-08T00:00:00.000Z,2023-10-08T00:00:00.000Z,2023-10-09T00:00:00.000Z,2023-10-16T00:00:00.000Z,0.0,1.0,0.0
2,1981,2.243558e+08,95754618.67,71549737.00,7469.0,Major Disaster,Flood,ND,8,2011-05-10T00:00:00.000Z,2011-05-06T00:00:00.000Z,2011-02-14T00:00:00.000Z,2011-07-20T00:00:00.000Z,0.0,1.0,1.0
3,1802,1.881275e+07,NaN,2710679.00,NaN,Major Disaster,Severe Storm,KY,4,2008-10-09T00:00:00.000Z,2008-09-26T00:00:00.000Z,2008-09-12T00:00:00.000Z,2008-09-14T00:00:00.000Z,0.0,1.0,1.0
4,4317,7.731984e+07,12527583.31,17801245.73,1978.0,Major Disaster,Flood,MO,7,2017-06-02T00:00:00.000Z,2017-05-24T00:00:00.000Z,2017-04-28T00:00:00.000Z,2017-05-11T00:00:00.000Z,0.0,1.0,1.0

In [18]:
df['incidentType'].value_counts()

incidentType
Fire                   1694
Severe Storm            922
Hurricane               355
Flood                   278
Biological              166
Snowstorm               137
Severe Ice Storm         66
Tornado                  61
Drought                  36
Tropical Storm           35
Winter Storm             29
Other                    26
Typhoon                  24
Coastal Storm            21
Earthquake               19
Mud/Landslide            12
Freezing                  5
Toxic Substances          5
Dam/Levee Break           4
Tsunami                   3
Human Cause               2
Straight-Line Winds       2
Terrorist                 2
Volcanic Eruption         2
Chemical                  1
Fishing Losses            1
Tropical Depression       1
Name: count, dtype: int64